### ISSUE TITLE
Error in the naming of "math_inline_close" token

### ISSUE THREAD

**Issue by darkuranium** [runarberg/markdown-it-math#1]
The token "math_inline_close" is mistakenly named --- its name is "math_inline_close," instead (note the comma).

The error is in `index.js`, line L124: https://github.com/runarberg/markdown-it-math/blob/ff8bd051c55c826363dbceed7e856c4d77d39151/index.js#L124

The reason this matters is that I was implementing a custom renderer for the open and close tags; that's because I do not want the `<math>` tags in my output, because my output is not (necessarily) MathML.

**Comment by darkuranium** [comment]
I should also note my current workaround:

``` javascript
mdit.renderer.rules.math_inline_close = mdit.renderer.rules['math_inline_close,'] = function(...) { ... }
```

**Comment by runarberg** [comment]
Thanks for telling me, I've fixed the issue now :)
