### ISSUE TITLE
Allow single line block math

### ISSUE THREAD

**Issue by runarberg** [runarberg/markdown-it-math#11]
Currently we ignore everything between opening block delimiters and the next newline. The reason being that future versions could use that space for arguments, as is the case with code fences. However, many people are used to write their block expressions in a single line, comming from typesetting systems like TeX, and it can be inconvenient for them to change their style when moving to markdown. Therefor we should allow single line block expressions to be allowed by default and perhaps in future versions make the code fence behavior optional.

**Comment by leipert** [comment]
See #10 ;)
