### ISSUE TITLE
about Inline parser

### ISSUE THREAD

**Issue by Rokt33r** [runarberg/markdown-it-math#14]
```
$$a$$b$$c$$

$$\mathbf{a}$$b$$c$$
```

The first code works fine. markdown-it-math tokenize `a` and `c` only.
But, the second code doesn't work. It try to parse `\mathbf{a}$$b`.

What makes this difference?
And, what should I do to parse the second code just like the first?

**Comment by cshaa** [comment]
It works correctly for me... 🤔
---
![obrazek](https://user-images.githubusercontent.com/1671665/44861605-206f8580-ac79-11e8-904d-6a88d5f0c0bf.png)
