### ISSUE TITLE
not match some text

### ISSUE THREAD

**Issue by xiaokaike** [runarberg/markdown-it-math#19]
``` text
xxxx$$-2x<4$$
```

i test on [dillinger](http://dillinger.io/) which use _markdown-it-math_ to parse latex

the result 
![image](https://cloud.githubusercontent.com/assets/4251499/14483148/86c45b04-0176-11e6-9241-4e63806b15f9.png)

but i add a space before _$$_,  it work 

``` text
xxxx $$-2x<4$$
```

![image](https://cloud.githubusercontent.com/assets/4251499/14483168/b4cc6910-0176-11e6-9d29-de676d4c5814.png)

**Comment by runarberg** [comment]
This is definitely not the intended behaviour I wonder if it is taking the leading hyphen to be a whitespace character https://github.com/runarberg/markdown-it-math/blob/master/test/fixtures/default.txt#L21-L42

**Comment by xiaokaike** [comment]
Like other inline markup, whitespace immediately after opening is not allowed

this latex without any whitespace 
it not working when `-` is after opening 
_no working_

``` text
xxxx$$-2x<4$$
```

_working_

``` text
xxxx$$2x<4$$
```

**Comment by runarberg** [comment]
Merged 4.0.0
