### ISSUE TITLE
`String.prototype.repeat` is not available in all JS engines

### ISSUE THREAD

**Issue by darkuranium** [runarberg/markdown-it-math#2]
There is a problem with your use of `String.prototype.repeat` --- namely, it is not supported in all JS engines, as it is not part of standard ECMAScript (rather, it exists in the ECMAScript 6 proposal).

In my particular case, it is not available in node.js, version 0.10.29 (this is the version distributed with Debian Stable):

```
$ nodejs -v
v0.10.29
```

You are using that function in two places, both in `index.js`:
- [index.js:L119](https://github.com/runarberg/markdown-it-math/blob/b9dedd57ec1c89b1ceaaa8b9b2f6a57c38e7651c/index.js#L119)
- [index.js:L125](https://github.com/runarberg/markdown-it-math/blob/b9dedd57ec1c89b1ceaaa8b9b2f6a57c38e7651c/index.js#L125)

I was able to work around this issue with a polyfill available on the Mozilla Developer Network: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

Of course, a polyfill might be too intrusive, since it changes `String.prototype` (though I don't care much, personally), but perhaps you should at least be able to modify that function to suit your needs.

**Comment by runarberg** [comment]
Thanks, I replaced it with a general function
